### ISSUE TITLE
wrong picture for Two Regular Hexagons II

### ISSUE THREAD

**Issue by vit-tucek** [loopspace/Mathforge-Notes#1]
There is a wrong picture at [Two Regular Hexagons II](https://notes.mathforge.org/notes/published/two+regular+hexagons+ii )

**Comment by loopspace** [comment]
Looks like I got the various "regular hexagons" puzzles mixed up.  Thanks for spotting it.

**Comment by loopspace** [comment]
I think I've fixed this now.
