### ISSUE TITLE
Caty Agg puzzle oct 19 2019

### ISSUE THREAD

**Issue by Areaequalspircubed** [loopspace/Mathforge-Notes#4]
Solution is incorrect. It is 75 not 150 you have assumed 5 is radius not diameter in last calc.

**Comment by loopspace** [comment]
I agree, thanks for pointing it out.

(Link to puzzle so I can easily find it when I'm able to fix it: https://notes.mathforge.org/notes/published/three+circles+in+a+rectangle+ii+solution )

**Comment by loopspace** [comment]
I've edited the solution.

**Comment by Areaequalspircubed** [comment]
Thank you. Just a bit about me:  Elec. Eng. and maths at SJC Cam. 25 years at Intel Corp, ex  software/hardware/firmware engineer, now retired. During C19 lockdowns became  "recreational" mathematician to fight the boredom and still enjoy maths puzzles particularly solving them via "The Calculus" and anything by Caty Agg. Lifetime fan of Einstein SR and GR.  Party trick of explaining SR to non mathematician in 3 minutes. 😀 Best wishes, Simon.Sent from my Samsung Galaxy A33 5G
-------- Original message --------From: Loop Space ***@***.***> Date: 08/08/2023  21:28  (GMT+00:00) To: loopspace/Mathforge-Notes ***@***.***> Cc: Areaequalspircubed ***@***.***>, Author ***@***.***> Subject: Re: [loopspace/Mathforge-Notes] Caty Agg puzzle oct 19 2019 (Issue
  #4) 
I've edited the solution.
